// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc319.BobBAE2013.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc319.BobBAE2013.Robot;
/**
 *
 */
public class  AutonomousCommand extends Command {
    boolean finished = false;
    public AutonomousCommand() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	requires(Robot.shooter);
        requires(Robot.pneumatics);
        requires(Robot.driveTrain);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        finished = false;
        Robot.shooter.Spin();//Spin up wheels
        Timer.delay(3);
        Robot.shooter.TriggerExtend();//Reset Trigger
        Timer.delay(.2);
        Robot.shooter.FeederExtend();//Drop Frisbee
        Timer.delay(1.5);
        Robot.shooter.TriggerRetract();//Fire frisbee
        Timer.delay(.2);
        Robot.shooter.FeederRetract();//Reset Feeder
        Timer.delay(.4);
        
        Robot.shooter.TriggerExtend();//Reset Trigger
        Timer.delay(.2);
        Robot.shooter.FeederExtend();//Drop Frisbee
        Timer.delay(1.5);
        Robot.shooter.TriggerRetract();//Fire frisbee
        Timer.delay(.2);
        Robot.shooter.FeederRetract();//Reset Feeder
        Timer.delay(.4);
                
        Robot.shooter.TriggerExtend();//Reset Trigger
        Timer.delay(.2);
        Robot.shooter.FeederExtend();//Drop Frisbee
        Timer.delay(1.5);
        Robot.shooter.TriggerRetract();//Fire frisbee
        Timer.delay(.2);
        Robot.shooter.FeederRetract();//Reset Feeder
        Timer.delay(.4);
        //Robot.shooter.Stop();
        Robot.shooter.TriggerExtend();//Reset Trigger
      
        Robot.driveTrain.DriveBack();//Drives backwards from pyramid
        Timer.delay(1.5);
        Robot.driveTrain.TurnAround();//Turns Bob around
        Timer.delay(1);
        Robot.driveTrain.Stop();//Stops Bob
        
        Robot.pneumatics.CompressorOn();//Turns compressor on
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        finished = true;
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return finished;
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.shooter.Stop();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
